// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXfVHKRea6KTEuFaV9jOWhxUaB6HkFLY',
    appId: '1:421609505376:web:5fcfb6395d020c5793b905',
    messagingSenderId: '421609505376',
    projectId: 'testas-c4487',
    authDomain: 'testas-c4487.firebaseapp.com',
    storageBucket: 'testas-c4487.appspot.com',
    measurementId: 'G-S7SGE85B2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2Ap32mknyxTXGVQHq9HmIsafPxjKQgk',
    appId: '1:421609505376:android:fb252077e6af7f9193b905',
    messagingSenderId: '421609505376',
    projectId: 'testas-c4487',
    storageBucket: 'testas-c4487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLAHnpHfWxrsGkEin7Cy2WWUZLhrsdd8',
    appId: '1:421609505376:ios:9b5b52cf7bcdb64493b905',
    messagingSenderId: '421609505376',
    projectId: 'testas-c4487',
    storageBucket: 'testas-c4487.appspot.com',
    iosClientId: '421609505376-l2m99q8kgvo2uj87o2f3qjs544mn0kru.apps.googleusercontent.com',
    iosBundleId: 'com.As.hjore1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLAHnpHfWxrsGkEin7Cy2WWUZLhrsdd8',
    appId: '1:421609505376:ios:9b5b52cf7bcdb64493b905',
    messagingSenderId: '421609505376',
    projectId: 'testas-c4487',
    storageBucket: 'testas-c4487.appspot.com',
    iosClientId: '421609505376-l2m99q8kgvo2uj87o2f3qjs544mn0kru.apps.googleusercontent.com',
    iosBundleId: 'com.As.hjore1',
  );
}
